name = "DevRegistry"
uuid = "c42d65c5-f4a5-46cd-937d-ca6575acc600"
repo = "git@github.com:00krishna-opensource/DevRegistry.git"
description = "Registry for package under development."

[packages]
603251c8-9ed4-4db3-9104-3e0302b27083 = { name = "JuliaGendUniv_Types", path = "J/JuliaGendUniv_Types" }
ec49cb16-2c8f-4e2a-bcf7-d6761e85d5de = { name = "DemoInertiaPreprocess", path = "D/DemoInertiaPreprocess" }
ee0bee73-3820-4a52-80b0-6c7d86c4e1a7 = { name = "JuliaGendUniv", path = "J/JuliaGendUniv" }
