name = "DevRegistry"
uuid = "c42d65c5-f4a5-46cd-937d-ca6575acc600"
repo = "git@github.com:00krishna-opensource/DevRegistry.git"
description = "Registry for package under development."

[packages]
ec49cb16-2c8f-4e2a-bcf7-d6761e85d5de = { name = "DemoInertiaPreprocess", path = "D/DemoInertiaPreprocess" }
